server:
  port: 7001
logging:
  level:
    com.sidh.springboot.practice.genericdb.ui: debug
#    root: trace
spring:
  mustache:
    suffix: .html
    prefix: file:ui-layer/src/main/resources/templates/
  resources:
    static-locations:
      - file:ui-layer/src/main/resources/static/
metamodel:
  header:
    title: Generic Metamodel Framework
    subtitle: metamodel tool
external:
  dblayer:
    baseurl: http://localhost:7000
    ot:
      getOnePath: /objectType/%s
      getChildrenPath: /objectType/%s/children
      getChildrenTree: /objectType/%s/childrenTree
      getBoundAttrs: /objectType/%s/attribute