server:
  port: 7001
logging:
  level:
    root: debug
spring:
  mustache:
    suffix: .html
metamodel:
  header:
    title: Generic Metamodel Framework
    subtitle: metamodel tool
external:
  dblayer:
    baseurl: http://localhost:7000
    ot:
      getOnePath: /objectType/%s
      getChildrenPath: /objectType/%s/children
      getChildrenTree: /objectType/%s/childrenTree

